# Generated by Django 2.2.6 on 2021-06-27 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_post_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
        migrations.RemoveField(
            model_name='group',
            name='slug',
        ),
    ]
