# Generated by Django 2.2.6 on 2021-06-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210627_1544'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
